name: main

on: 
  push:
    branches: 
      - main


jobs:
  push-scenarios:
    runs-on: ubuntu-latest
    name: A job to push healthbot scenarios
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Push Scenarios action step
      id: push-scenarios
      uses: pjirsa/healthbot-template-push@v1.4.2
      with:
        tenant-name: ${{ secrets.TENANT_NAME }}
        api-secret: ${{ secrets.API_KEY }}
        template-file: '${{ github.workspace }}/template.json'
